# Generated by Django 6.0.2 on 2026-02-15 23:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_customuser_options_historicalcustomuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrainDump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('energy_level', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10)),
                ('input_text', models.TextField()),
                ('source', models.CharField(choices=[('web', 'web'), ('mobile', 'mobile'), ('api', 'api')], default='web', max_length=10)),
                ('word_count', models.PositiveIntegerField(blank=True, editable=False, help_text='Set from input_text on save; optional DB-generated column in Postgres.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brain_dumps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'brain_dumps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quick_catch_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_energy_level', models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10)),
                ('timezone', models.CharField(default='America/New_York', max_length=63)),
                ('email_opt_in', models.BooleanField(default=True)),
                ('neurodivergent_focus', models.CharField(choices=[('adhd', 'adhd'), ('autistic', 'autistic'), ('audhd', 'audhd'), ('unspecified', 'unspecified')], default='unspecified', max_length=20)),
            ],
            options={
                'db_table': 'profiles',
                'indexes': [models.Index(fields=['email_opt_in'], name='profiles_email_o_8e14d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='TriageRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model_name', models.CharField(max_length=128)),
                ('prompt_version', models.CharField(default='v1', max_length=32)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, default=0.2, max_digits=3, null=True)),
                ('top_3_task_ids', models.JSONField(default=list, help_text='List of triage_tasks.id (UUIDs as strings).')),
                ('blockers', models.JSONField(default=list)),
                ('action_plan_md', models.TextField()),
                ('summary_one_liner', models.CharField(blank=True, max_length=512, null=True)),
                ('detected_crisis', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('token_in', models.PositiveIntegerField(blank=True, null=True)),
                ('token_out', models.PositiveIntegerField(blank=True, null=True)),
                ('dump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_runs', to='quick_catch.braindump')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'triage_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_after', models.DateTimeField(auto_now_add=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=512)),
                ('body_md', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sent', 'sent'), ('failed', 'failed'), ('canceled', 'canceled')], default='queued', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, max_length=256, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_catch_emails', to=settings.AUTH_USER_MODEL)),
                ('triage_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='quick_catch.triagerun')),
            ],
            options={
                'db_table': 'emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=512)),
                ('micro_steps', models.JSONField(default=list)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('rank_order', models.PositiveIntegerField(blank=True, null=True)),
                ('is_top3', models.BooleanField(default=False)),
                ('best_energy', models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], max_length=10, null=True)),
                ('friction_score', models.DecimalField(blank=True, decimal_places=2, help_text='0..10, higher = more aversive.', max_digits=4, null=True)),
                ('category', models.CharField(blank=True, help_text='e.g. admin, sales, dev, personal (AI inferred).', max_length=64, null=True)),
                ('evidence_spans', models.JSONField(default=list, help_text='e.g. [{"start": 120, "end": 180, "text": "..."}]')),
                ('triage_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_tasks', to='quick_catch.triagerun')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'triage_tasks',
                'ordering': ['triage_run', 'rank_order'],
            },
        ),
        migrations.AddIndex(
            model_name='braindump',
            index=models.Index(fields=['user', '-created_at'], name='brain_dumps_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='triagerun',
            index=models.Index(fields=['dump', '-created_at'], name='triage_runs_dump_created_idx'),
        ),
        migrations.AddIndex(
            model_name='triagerun',
            index=models.Index(fields=['user', '-created_at'], name='triage_runs_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='triagerun',
            constraint=models.UniqueConstraint(fields=('dump', 'prompt_version'), name='triage_runs_dump_prompt_version_uniq'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status', 'send_after'], name='emails_status_send_after_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['user', '-created_at'], name='emails_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='triagetask',
            index=models.Index(fields=['triage_run', 'rank_order'], name='triage_tasks_run_rank_idx'),
        ),
        migrations.AddIndex(
            model_name='triagetask',
            index=models.Index(fields=['user', '-created_at'], name='triage_tasks_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='triagetask',
            index=models.Index(fields=['user', 'is_top3', '-created_at'], name='triage_tasks_is_top3_idx'),
        ),
    ]
